repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.6.0
        hooks:
            -   id: end-of-file-fixer
            -   id: trailing-whitespace
            -   id: check-toml
            -   id: check-yaml
            -   id: check-merge-conflict
            -   id: mixed-line-ending
                args: [ "--fix=lf" ]
    -   repo: https://github.com/bufbuild/buf
        rev: v1.32.0
        hooks:
            -   id: buf-lint
            -   id: buf-format
